server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
